# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'starter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(335, 36, 81, 31))
        self.startButton.setObjectName("startButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 30, 91, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 60, 81, 16))
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(150, 20, 111, 31))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(150, 60, 121, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.mainImageFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainImageFrame.setGeometry(QtCore.QRect(120, 90, 231, 141))
        self.mainImageFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainImageFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainImageFrame.setObjectName("mainImageFrame")
        self.plateFrame = QtWidgets.QFrame(self.centralwidget)
        self.plateFrame.setGeometry(QtCore.QRect(180, 240, 101, 51))
        self.plateFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plateFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plateFrame.setObjectName("plateFrame")
        self.skipButton = QtWidgets.QPushButton(self.centralwidget)
        self.skipButton.setGeometry(QtCore.QRect(20, 410, 81, 41))
        self.skipButton.setObjectName("skipButton")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(205, 406, 81, 41))
        self.saveButton.setObjectName("saveButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.label.setText(_translate("MainWindow", "Images Folder"))
        self.label_2.setText(_translate("MainWindow", "Output Folder"))
        self.skipButton.setText(_translate("MainWindow", "Skip"))
        self.saveButton.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
