name: alpd-gpu

dependencies:
  - python==3.9
  - pip
  - matplotlib
  - opencv
  - cudnn
  - cudatoolkit==10.1.243
  - pip:
    - tensorflow-gpu
    - opencv-python
    - lxml
    - tqdm
    - absl-py
    - easydict
    - pillow
    - pytesseract
